apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-configuration
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER:     {{ .Values.username | toString | b64enc }}
  POSTGRES_DB:       {{ .Values.database | toString | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.password | toString | b64enc }}
  PGUSER:            {{ .Values.username | toString | b64enc }}
  PGDATABASE:        {{ .Values.database | toString | b64enc }}
{{- if .Values.password }}
  PGPASSWORD:        {{ .Values.password | toString | b64enc }}
{{- end }}
